variables:
  MAVEN_DOCKER_IMAGE: "maven:3.6.0-jdk-11"
  JDK_WIN_URL: "https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip"

stages:
  - build
  - deploy
  - owasp

build:
  image: $MAVEN_DOCKER_IMAGE
  stage: build
  except:
    - tags
  script:
    - pushd Client
    - mvn -B -Djavafx.platform=win clean package
    - popd
    - mv Client/target/*.exe .
  artifacts:
    paths:
      - ./*.exe
    expire_in: 1 hour

build-release:
  image: $MAVEN_DOCKER_IMAGE
  stage: build
  only:
    - tags
  script:
    - pushd Client
    - mvn -B versions:set -DnewVersion=${CI_COMMIT_REF_NAME}
    - mvn -B -Djavafx.platform=win clean package
    - popd
    - mv Client/target/*.exe .
  artifacts:
    paths:
      - ./*.exe
    expire_in: 1 hour

deploy:
  image: alpine
  stage: deploy
  only:
    - tags
  dependencies:
    - build-release
  script:
    - apk update && apk add ca-certificates && update-ca-certificates && apk add openssl wget unzip zip
    - wget $JDK_WIN_URL && unzip *.zip && rm *.zip && mv jdk* jdk
    - mkdir lual-client && mv jdk lual-client/jdk && mv ./*.exe lual-client/
    - zip -r lual-client.zip lual-client
  artifacts:
    paths:
      - ./*.zip
    expire_in: 1 day

owasp:
  image: $MAVEN_DOCKER_IMAGE
  stage: owasp
  script:
    - pushd Client
    - mvn -B -Djavafx.platform=win dependency-check:check
    - popd
    - mv Client/target/dependency-check-report.html .
  artifacts:
    paths:
      - ./*.html
    expire_in: 1 day
